# -*- coding: utf-8 -*-
"""minhabassededados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5la7yGaQl9DHv9q8z04gbMAXUpz2K5Z

Importando as Bibliotecas
"""

import pandas as pd

"""Coletando as planilhas das Ligas Principais"""

# Inglaterra 1
ENG1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/E0.csv")
ENG1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/E0.csv")
ENG1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E0.csv")

ENG1 = [ENG1_01,ENG1_02,ENG1_03]
ENG1 = pd.concat(ENG1)
ENG1['Liga'] = 'Inglaterra 1'

# Inglaterra 2
ENG2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/E1.csv")
ENG2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/E1.csv")
ENG2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/E1.csv")


ENG2 = [ENG2_01,ENG2_02,ENG2_03]
ENG2 = pd.concat(ENG2)
ENG2['Liga'] = 'Inglaterra 2'

# Escócia 1
SCO1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/SC0.csv")
SCO1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/SC0.csv")
SCO1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SC0.csv")

# SCO1 = [SCO1_01,SCO1_02,SCO1_03,SCO1_04,SCO1_05,SCO1_06,SCO1_07,SCO1_08,SCO1_09,SCO1_10]
SCO1 = [SCO1_01,SCO1_02,SCO1_03]
SCO1 = pd.concat(SCO1)
SCO1['Liga'] = 'Escócia 1'

# Alemanha 1
GER1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/D1.csv")
GER1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/D1.csv")
GER1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D1.csv")

GER1 = [GER1_01,GER1_02,GER1_03]
GER1 = pd.concat(GER1)
GER1['Liga'] = 'Alemanha 1'

# Alemanha 2
GER2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/D2.csv")
GER2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/D2.csv")
GER2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/D2.csv")

GER2 = [GER2_01,GER2_02,GER2_03]
GER2 = pd.concat(GER2)
GER2['Liga'] = 'Alemanha 2'

# Itália 1
ITA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/I1.csv")
ITA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/I1.csv")
ITA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I1.csv")

ITA1 = [ITA1_01,ITA1_02,ITA1_03]
ITA1 = pd.concat(ITA1)
ITA1['Liga'] = 'Itália 1'

# Itália 2
ITA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/I2.csv")
ITA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/I2.csv")
ITA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/I2.csv")

# ITA2 = [ITA2_01,ITA2_02,ITA2_03,ITA2_04,ITA2_05,ITA2_06,ITA2_07,ITA2_08,ITA2_09,ITA2_10]
ITA2 = [ITA2_01,ITA2_02,ITA2_03]
ITA2 = pd.concat(ITA2)
ITA2['Liga'] = 'Itália 2'

# Espanha 1
SPA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/SP1.csv")
SPA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/SP1.csv")
SPA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP1.csv")

SPA1 = [SPA1_01,SPA1_02,SPA1_03]
SPA1 = pd.concat(SPA1)
SPA1['Liga'] = 'Espanha 1'

# Espanha 2
SPA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/SP2.csv")
SPA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/SP2.csv")
SPA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/SP2.csv")

SPA2 = [SPA2_01,SPA2_02,SPA2_03]
SPA2 = pd.concat(SPA2)
SPA2['Liga'] = 'Espanha 2'

# França 1
FRA1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/F1.csv")
FRA1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/F1.csv")
FRA1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F1.csv")

FRA1 = [FRA1_01,FRA1_02,FRA1_03]
FRA1 = pd.concat(FRA1)
FRA1['Liga'] = 'França 1'

# França 2
FRA2_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/F2.csv")
FRA2_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/F2.csv")
FRA2_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/F2.csv")

FRA2 = [FRA2_01,FRA2_02,FRA2_03]
FRA2 = pd.concat(FRA2)
FRA2['Liga'] = 'França 2'

# Holanda 1
NET1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/N1.csv")
NET1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/N1.csv")
NET1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/N1.csv")

NET1 = [NET1_01,NET1_02,NET1_03]
NET1 = pd.concat(NET1)
NET1['Liga'] = 'Holanda 1'

# Bélgica 1
BEL1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/B1.csv")
BEL1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/B1.csv")
BEL1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/B1.csv")

BEL1 = [BEL1_01,BEL1_02,BEL1_03]
BEL1 = pd.concat(BEL1)
BEL1['Liga'] = 'Bélgica 1'

# Portugal 1
POR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/P1.csv")
POR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/P1.csv")
POR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/P1.csv")

POR1 = [POR1_01,POR1_02,POR1_03]
POR1 = pd.concat(POR1)
POR1['Liga'] = 'Portugal 1'

# Turquia 1
TUR1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/T1.csv")
TUR1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/T1.csv")
TUR1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2122/T1.csv")

TUR1 = [TUR1_01,TUR1_02,TUR1_03]
TUR1 = pd.concat(TUR1)
TUR1['Liga'] = 'Turquia 1'

# Grécia 1
GRE1_01 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2324/G1.csv")
GRE1_02 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2223/G1.csv")
GRE1_03 = pd.read_csv("https://www.football-data.co.uk/mmz4281/2021/G1.csv")

GRE1 = [GRE1_01,GRE1_02,GRE1_03]
GRE1 = pd.concat(GRE1)
GRE1['Liga'] = 'Grécia 1'

"""Coletando as planilhas das Ligas Secundárias"""

ARG = pd.read_csv("https://www.football-data.co.uk/new/ARG.csv")
ARG['Liga'] = 'Argentina'

AUS = pd.read_csv("https://www.football-data.co.uk/new/AUT.csv")
AUS['Liga'] = 'Austria'

BRA = pd.read_csv("https://www.football-data.co.uk/new/BRA.csv")
BRA['Liga'] = 'Brasil'

CHI = pd.read_csv("https://www.football-data.co.uk/new/CHN.csv")
CHI['Liga'] = 'China'

DIN = pd.read_csv("https://www.football-data.co.uk/new/DNK.csv")
DIN['Liga'] = 'Dinamarca'

FIN = pd.read_csv("https://www.football-data.co.uk/new/FIN.csv")
FIN['Liga'] = 'Finlândia'

IRL = pd.read_csv("https://www.football-data.co.uk/new/IRL.csv")
IRL['Liga'] = 'Irlanda'

JAP = pd.read_csv("https://www.football-data.co.uk/new/JPN.csv")
JAP['Liga'] = 'Japão'

MEX = pd.read_csv("https://www.football-data.co.uk/new/MEX.csv")
MEX['Liga'] = 'México'

NOR = pd.read_csv("https://www.football-data.co.uk/new/NOR.csv")
NOR['Liga'] = 'Noruega'

POL = pd.read_csv("https://www.football-data.co.uk/new/POL.csv")
POL['Liga'] = 'Polônia'

ROM = pd.read_csv("https://www.football-data.co.uk/new/ROU.csv")
ROM['Liga'] = 'Romêmia'

RUS = pd.read_csv("https://www.football-data.co.uk/new/RUS.csv")
RUS['Liga'] = 'Rússia'

SUE = pd.read_csv("https://www.football-data.co.uk/new/SWE.csv")
SUE['Liga'] = 'Suécia'

SUI = pd.read_csv("https://www.football-data.co.uk/new/SWZ.csv")
SUI['Liga'] = 'Suíça'

USA = pd.read_csv("https://www.football-data.co.uk/new/USA.csv")
USA['Liga'] = 'USA'

"""Concatenando as Planilhas"""

df1 = [ENG1, ENG2, SCO1, GER1, GER2, ITA1, ITA2, SPA1, SPA2, FRA1, FRA2, NET1, BEL1, POR1, TUR1, GRE1]
df1 = pd.concat(df1)

df2 = [ARG, AUS, BRA, CHI, DIN, FIN, IRL, JAP, MEX, NOR, POL, ROM, RUS, SUE, SUI, USA]
df2 = pd.concat(df2)

"""Selecionando as colunas que serão utilizadas"""

df1 = df1[['Liga','Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR','B365H','B365D','B365A']]
df2 = df2[['League', 'Date', 'Home', 'Away', 'HG', 'AG', 'Res', 'PSCH', 'PSCD', 'PSCA']]

df1['Date'] = pd.to_datetime(df1['Date'], dayfirst=True, errors='coerce')
df2['Date'] = pd.to_datetime(df2['Date'], dayfirst=True, errors='coerce')

"""Renomeando as Colunas e unindo os DataFrames"""

df1.columns = ['Liga','Data','Mandante','Visitante','Gols Mandante','Gols Visitante','Resultado','Odds Mandante','Odds Empate','Odds Visitante']

df2.columns = ['Liga','Data','Mandante','Visitante','Gols Mandante','Gols Visitante','Resultado','Odds Mandante','Odds Empate','Odds Visitante']

df = [df1, df2]
df = pd.concat(df)

"""Visualizando o Resultado Final"""

df

df.info()

df = df.dropna()

df.info()
